name: pavra_server_server
description: Starting point for a Serverpod server.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  serverpod: ^2.9.2
  redis: ^4.0.0
  http: ^1.2.0
  logging: any
  supabase: ^2.3.5
  dotenv: ^4.2.0

dev_dependencies:
  lints: '>=3.0.0 <7.0.0'
  test: '^1.24.2'
  serverpod_test: ^2.9.2

